### ISSUE TITLE
unsafeHTML doesn't support HTML entities

### ISSUE THREAD

**Issue by TEirola** [mubanjs/muban-template#5]
I had an issue with my project with the HTML entities not being decoded. 
We have used unsafeHTML to print the content, for example for the heading component, but also for other components. 
For example: 
This is the string coming from the backend: `"Command &amp; Conquer"`
It won't be converted to `"Command & Conquer"`, but it will be printed as it comes from the backend.

I solved it by using unescape from lodash inside the unsafeHTML, but ideally, unsafeHTML would handle this by itself.

**Comment by ThaNarie** [comment]
`unsafeHTML` will probably be deprecated/removed, since it doesn't work correctly with HTML entities (due to the way the template function works, and adding `unescape` might give issues in other scenarios).

Instead use `dangerouslySetInnerHTML`.

More details in the readme:
https://github.com/mubanjs/muban-template#about-special-characters
